# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nina.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(418, 604)



        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "../../../../Downloads/helper_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: QLinearGradient(x1: 0, y1: 0, \n"
                                 "                            x2: 0, y2: 1, \n"
                                 "                            stop: 0.2 rgba(96, 93, 246, 1), \n"
                                 "                            stop: 1   rgba(22, 2, 149, 1));\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_hello = QtWidgets.QLabel(self.centralwidget)
        self.label_hello.setEnabled(True)
        self.label_hello.setGeometry(QtCore.QRect(103, 40, 231, 131))
        self.label_hello.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_hello.setFont(font)
        self.label_hello.setStyleSheet("background-color:#00FFFFFF;\n"
                                       "color: #FFFFFE;")
        self.label_hello.setLineWidth(1)
        self.label_hello.setObjectName("label_hello")
        self.listView_answer = QtWidgets.QListView(self.centralwidget)
        self.listView_answer.setGeometry(QtCore.QRect(90, 150, 256, 192))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.listView_answer.setFont(font)
        self.listView_answer.setStyleSheet("background-color: #00FFFFFF;\n"
                                           "border-color: #00FFFFFF;\n"
                                           "color: #ffffff;\n"
                                           "\n"
                                           "border-radius: 20px;")
        self.listView_answer.setProperty("showDropIndicator", True)
        self.listView_answer.setObjectName("listView_answer")
        self.Say = QtWidgets.QToolButton(self.centralwidget)
        self.Say.setGeometry(QtCore.QRect(174, 450, 75, 75))
        self.Say.setStyleSheet("background-color: #00FFFFFF;\n"
                                      "border-radius:35px;\n"
                                      "\n"
                                      "\n"
                                      "")
        self.Say.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/voice-assistant.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Say.setIcon(icon1)
        self.Say.setIconSize(QtCore.QSize(72, 72))
        self.Say.setObjectName("toolButton")

        

        self.Wave2 = QtWidgets.QPushButton(self.centralwidget)
        self.Wave2.setGeometry(QtCore.QRect(0, 210, 430, 131))
        self.Wave2.setStyleSheet("background-color: #00FFFFFF;\n"
                                      "\n"
                                      "")
        self.Wave2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "img/pngkey.com-waves-png-55053.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wave2.setIcon(icon2)
        self.Wave2.setIconSize(QtCore.QSize(430, 250))
        self.Wave2.setObjectName("pushButton")
        self.circle = QtWidgets.QPushButton(self.centralwidget)
        self.circle.setGeometry(QtCore.QRect(0, 200, 430, 131))
        self.circle.setStyleSheet("background-color: #00FFFFFF;\n"
                                        "\n"
                                        "")
        self.circle.setText("")
        self.circle.setIcon(icon2)
        self.circle.setIconSize(QtCore.QSize(430, 250))
        self.circle.setObjectName("pushButton_2")
        self.Exit = QtWidgets.QToolButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(370, 10, 35, 35))
        self.Exit.setStyleSheet("background-color: #00FFFFFF;\n"
                                        "border-radius:35px;\n"
                                        "\n"
                                        "\n"
                                        "")
        # self.Exit.setText("")
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap("img/cross-mark(1).png"),
        #                 QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.Exit.setIcon(icon3)
        # self.Exit.setIconSize(QtCore.QSize(40, 40))
        # self.Exit.setObjectName("toolButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nina"))
        self.label_hello.setText(_translate(
            "MainWindow", "Привет, чем могу помочь ?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
